#:schema node_modules/wrangler/config-schema.json
name = "sublink
"
main = "src/index.js"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "14a85f121bb54f1abf727f8897984b54" }
]
